# FROM node:16.13.1 as builder
FROM node:lts-alpine as builder

WORKDIR '/app' 
# WORKDIR /home/node/app

COPY package.json .

# RUN npm install --verbose
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable
# COPY --from=builder /home/node/app/build /usr/share/nginx/html
COPY --from=builder /app/build /usr/share/nginx/html
