version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - WATCHPACK_POLLING=true # THIS WORKS !!!!!!!!!!
      # - CHOKIDAR_USEPOLLING=true # Useless or didnt work, this was an attempt to make the real time change work
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    
