# FROM node:lts-alpine
FROM node:16.13.1 
# FROM node:13.12.0-alpine
# FROM node:18 AS node

WORKDIR '/app' 

COPY package.json .
RUN npm install --verbose
# RUN npm install @testing-library/react@latest

COPY . .

# ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "start"]